### ISSUE TITLE
TypeError("Cannot call a class as a function")

### ISSUE THREAD

**Issue by sivamca19** [MYOB-Technology/cucumber-js-selenium-webdriver-example#2]
cucumber-js-selenium-webdriver-example/features/support/pages/Base.js:9
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
                                                                                            ^

TypeError: Cannot call a class as a function
    at _classCallCheck (path/cucumber-js-selenium-webdriver-example/features/support/pages/Base.js:9:99)
    at Object.Base (path/cucumber-js-selenium-webdriver-example/features/support/pages/Base.js:3:22)
    at /Users/siva/Desktop/projects/packetmedia/cucumber-js-selenium-webdriver-example/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:67:33
    at Array.forEach (native)
    at Object.wrapper (path/cucumber-js-selenium-webdriver-example/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:62:15)
    at Object.initializer (path/cucumber-js-selenium-webdriver-example/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:23:37)
    at Object.Library (path/cucumber-js-selenium-webdriver-example/node_modules/cucumber/lib/cucumber/support_code/library.js:133:25)
    at Object.getSupportCodeLibrary (path/cucumber-js-selenium-webdriver-example/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:10:58)
    at Object.getSupportCodeLibrary (path/cucumber-js-selenium-webdriver-example/node_modules/cucumber/lib/cucumber/cli/configuration.js:128:32)
    at Object.getSupportCodeLibrary (path/cucumber-js-selenium-webdriver-example/node_modules/cucumber/lib/cucumber/runtime.js:44:46)
npm ERR! Test failed.  See above for more details.

Kindly help me...

**Comment by dueckes** [comment]
This is caused by a change made in cucumber 1.3.0 - all files under the features directory are autoloaded by default.

This can be prevented by using the --require command line option.

Fix has now been pushed, together with updates to the latest versions of all libraries and the latest Node LTS.
